version: "3.9"
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - ${EXPOSE_IP:-127.0.0.1}:${MONGODB_PORT:-27017}:27017

  madiify-auth:
    image: madiify-auth:latest
    build: ./authentication/.
    restart: always
    env_file:
      - ./authentication/.env
    ports:
      - 3000:3000
